#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FactoryBarcode.Resource", IsApplication=true)]

namespace FactoryBarcode
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::FactoryBarcode.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::FactoryBarcode.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::FactoryBarcode.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int menu_text_color = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int xam_blue = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int xam_dark_blue = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int xam_gray = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int xam_green = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int xam_light_gray = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int xam_purple = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Barcode = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Barcode2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int custom_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int NoTitle = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int NoTitle2 = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int btnBack = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int btnInsert = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int btnScan = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int btn_delete = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int btn_open = 2131099654;
			
			// aapt resource value: 0x7f06000f
			public const int contentFrame = 2131099663;
			
			// aapt resource value: 0x7f060005
			public const int descrip = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int editDescrip = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int editUri = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int listview = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int refresher = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int refresher1 = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int txtTitle = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int webview = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Index1 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ItemRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int zxingscanneractivitylayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int zxingscannerfragmentlayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
