#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FactoryBarcode.Resource", IsApplication=true)]

namespace FactoryBarcode
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::FactoryBarcode.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::FactoryBarcode.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::FactoryBarcode.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int menu_text_color = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int xam_blue = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int xam_dark_blue = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int xam_gray = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int xam_green = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int xam_light_gray = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int xam_purple = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Barcode = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Barcode2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int custom_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon512 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Settings = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000a
			public const int NoTitle = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int NoTitle2 = 2131165196;
			
			// aapt resource value: 0x7f070011
			public const int action_add = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int action_settings = 2131165202;
			
			// aapt resource value: 0x7f070009
			public const int btnBack = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int btnScan = 2131165197;
			
			// aapt resource value: 0x7f070008
			public const int btn_delete = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int btn_open = 2131165191;
			
			// aapt resource value: 0x7f070010
			public const int contentFrame = 2131165200;
			
			// aapt resource value: 0x7f070006
			public const int descrip = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int editDescrip = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int editUri = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int infoTxtCredits = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int listview = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int refresher = 2131165198;
			
			// aapt resource value: 0x7f070004
			public const int refresher1 = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int txtTitle = 2131165195;
			
			// aapt resource value: 0x7f070000
			public const int txtWepApi = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int webview = 2131165199;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AppSetting = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Index1 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ItemRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int zxingscanneractivitylayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int zxingscannerfragmentlayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
